### ISSUE TITLE
helm-gtags-update-tags with C-u prefix not update tags in .h header files?

### ISSUE THREAD

**Issue by whatacold** [emacsorphanage/helm-gtags#175]
Hi,
  I'm using projectile, helm and helm-gtags to manage and navigate source code project,
Now I have a problem with helm-gtags: `helm-gtags-update-tags` with C-u prefix can update tags in .cpp source file, but it can't update tags in header files.

  What should I do to fix this?

**Comment by syohex** [comment]
Sorry very late reply. However I cannot reproduce this issue. Could you show us how to reproduce this issue in more detail ?

**Comment by whatacold** [comment]
Sorry that I don't use `heml-gtags` anymore, feel free to close this. If I happen to find any new issues someday, I will report back.
