### ISSUE TITLE
support `ggtags-find-tag-continue` like operation

### ISSUE THREAD

**Issue by yanglimingcn** [emacsorphanage/helm-gtags#191]
can helm-gtags support `ggtags-find-tag-continue` like operation?
when i find many tags,  then i will edit one of those, then continue find the next one.

**Comment by jcs090218** [comment]
Hi, I'm currently the maintainer of this package!

Just to let you know this package is stopped further develop. If you you wish this feature can be implemented to this package, please feel free to open PR to contribute to this package! Thanks! 😄

**Comment by syohex** [comment]
I don't understand ggtags.el well. Does `ggtags-find-tag-continue` behave like following snippet ?

```lisp
(defun helm-gtags-tag-continue ()
  (interactive)
  (unless (get-buffer helm-gtags--buffer)
    (error "Error: helm-gtags buffer is not existed."))
  (let ((next-candidate
         (with-current-buffer (get-buffer helm-gtags--buffer)
           (forward-line 1)
           (when (eobp)
             (error "No more candidate"))
           (buffer-substring-no-properties (point) (line-end-position)))))
    (helm-gtags--action-openfile next-candidate)))
```

**Comment by yanglimingcn** [comment]
yes like this

**Comment by yanglimingcn** [comment]
I found helm-gtags-resume, is the same like continue, thank you.
